version: '3.4'

services:
  db:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6-alpine
    networks:
      - redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - redis-data:/data

  core-main:
    <<: *app_base
    ports:
      - '3000:3000'
    networks:
      - database
      - socket
      - redis
    restart: always

  admin-panel:
    image: registry.github.com/vedoc/admin-panel:development
    build:
      context: ./Admin-Panel
      args:
        BUNDLE_WITHOUT: "development:test"
        FOLDERS_TO_REMOVE: "log tmp/cache"
        RAILS_ENV: "production"
        NODE_ENV: "production"
        GIT_CREDENTIALS: "your_git_credentials_here"
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    networks:
      - database

volumes:
  postgres-data:
  redis-data:

networks:
  database:
  redis:
