version: '3.8'

services:
  core_main:
    build:
      context: ./core-main
      args:
        FOLDERS_TO_REMOVE: 'tmp log'
        BUNDLE_WITHOUT: 'development test'
        RAILS_ENV: 'production'
        NODE_ENV: 'production'
        GIT_CREDENTIALS: "user:password"
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./core-main:/app
    command: sh -c "./docker/startup.sh"

  admin_panel:
    build:
      context: ./admin-panel
      args:
        FOLDERS_TO_REMOVE: 'tmp log'
        BUNDLE_WITHOUT: 'development test'
        RAILS_ENV: 'production'
        NODE_ENV: 'production'
        GIT_CREDENTIALS: "user:password"
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - db
      - mongo
    volumes:
      - ./admin-panel:/app
    command: sh -c "./docker/startup.sh"

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
