version: '3.8'

services:
  core_main:
    build:
      context: ./core-main
      args:
        FOLDERS_TO_REMOVE: 'tmp log'
        BUNDLE_WITHOUT: 'development test'
        RAILS_ENV: 'production'
        NODE_ENV: 'production'
        GIT_CREDENTIALS: "user:password"
    env_file: .env
    ports:
      - "3000:3000"
    command: sh -c "./docker/startup.sh"

  admin_panel:
    build:
      context: ./admin-panel
      args:
        FOLDERS_TO_REMOVE: 'tmp log'
        BUNDLE_WITHOUT: 'development test'
        RAILS_ENV: 'production'
        NODE_ENV: 'production'
        GIT_CREDENTIALS: "user:password"
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - core_main
    command: sh -c "./docker/startup.sh"
