version: '3.4'

services:
  db:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3


  redis:
    image: redis:6-alpine
    networks:
      - redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - redis-data:/data

  app: &app_base
    image: registry.github.com/vedoc/core-main:development
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs-current
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=development
        - NODE_ENV=development
        - GIT_CREDENTIALS=user:password
    environment:
      - APP_HOST=localhost:3000
      # Database
      - DB_HOST=db
      - DB_NAME=vedoc-api_development
      - DB_USER=postgres
      - DB_PASSWORD=password
      # Redis
      - REDIS_URL=redis://redis:6379/0
      - REDIS_SIDEKIQ_URL=redis://redis:6379/1
      # Mailer Credentials
      - APP_EMAIL=vedoc@team.com
      - MAIL_USERNAME=vedoc
      - MAIL_PASSWORD=foobar123
      - SMTP_DOMAIN=smtp.sendgrid.net
      # Stripe & Firebase
      - STRIPE_SECRET_KEY=foobar123
      - FIREBASE_SERVER_KEY=foobar123
      # AWS Credentials
      - AWS_ACCESS_KEY_ID=foobar123
      - AWS_SECRET_ACCESS_KEY=foobar123
      - AWS_BUCKET=foobar123
      - AWS_REGION=foobar123
      # Admin Credentials
      - ADMIN_EMAIL=admin@mail.com
      - ADMIN_PASSWORD=password
      # Mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - MONGO_DB=vedoc_chat
      - MONGO_HOST=mongo:27017
      - MONGO_COLLECTION=chats
    ports:
      - '3000:3000'
    networks:
      - database
      - socket
      - redis
      - mongo
    restart: always

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports:
      - 5000
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: 1m
      start_period: 1m

  admin:
    image: registry.github.com/vedoc/admin-panel:development
    build:
      context: ../Admin-Panel
      args:
        - ADDITIONAL_PACKAGES=nodejs-current
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=development
        - NODE_ENV=development
        - GIT_CREDENTIALS=user:password
    environment:
      - APP_HOST=localhost:3001
      - FIREBASE_SERVER_KEY=foobar123
      # Database
      - DB_HOST=db
      - DB_NAME=vedoc-api_development
      - DB_USER=postgres
      - DB_PASSWORD=password
      # Admin Credentials
      - ADMIN_EMAIL=admin@mail.com
      - ADMIN_PASSWORD=password
      # Mailer Credentials
      - APP_EMAIL=vedoc@team.com
      - MAIL_USERNAME=vedoc
      - MAIL_PASSWORD=foobar123
      - SMTP_DOMAIN=smtp.sendgrid.net
    ports:
      - '3001:3001'
    networks:
      - database

  mongo:
    image: mongo:4
    # command: --smallfiles
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  chat:
    image: registry.github.com/vedoc/vedoc-chat:development
    build: ../vedoc-chat
    restart: always
    # volumes: [ '../chat-node:/usr/src/app' ]
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DB: vedoc_chat
      MONGO_HOST: mongo
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS_TIMEOUT: 60
    links:
      - mongo
    networks:
      - socket  
      - mongo
    ports:
      - 8080:8080
      # - "8080:3000"

volumes:
  db-data:
  mongo-data:
  redis-data:

networks:
  socket:
  database:
  redis:
  mongo:
  