version: '3.4'

services:
  db:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_HOST: "${DB_HOST}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -h ${DB_HOST}"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:6-alpine
    networks:
      - redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - redis-data:/data

  app: &app_base
    image: registry.github.com/vedoc/core-main:latest
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs-current
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=development
        - NODE_ENV=development
        - GIT_CREDENTIALS=user:password
    environment:
      - APP_HOST=${APP_HOST}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
      - REDIS_SIDEKIQ_URL=redis://redis:6379/1
      - APP_EMAIL=${APP_EMAIL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FIREBASE_SERVER_KEY=${FIREBASE_SERVER_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    ports:
      - '3000:3000'
    networks:
      - database
      - socket
      - redis
      - mongo
    restart: always

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports:
      - 5000
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: 1m
      start_period: 1m

  admin:
    image: registry.github.com/vedoc/vedoc-admin:latest
    build:
      context: ../vedoc-admin
      args:
        - ADDITIONAL_PACKAGES=nodejs-current
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=development
        - NODE_ENV=development
        - GIT_CREDENTIALS=user:password
    environment:
      - APP_HOST=${APP_HOST}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_EMAIL=${APP_EMAIL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - FIREBASE_SERVER_KEY=${FIREBASE_SERVER_KEY}
    ports:
      - '3001:3001'
    networks:
      - database

  mongo:
    image: mongo:4
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  chat:
    image: registry.github.com/vedoc/vedoc-chat:latest
    build: ../vedoc-chat
    restart: always
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DB: vedoc_chat
      MONGO_HOST: mongo
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS_TIMEOUT: 60
    networks:
      - socket  
      - mongo
    ports:
      - 8080:8080

volumes:
  db-data:
  mongo-data:
  redis-data:

networks:
  socket:
  database:
  redis:
  mongo:
