default: &default
  adapter: postgis
  encoding: unicode
  username: postgres
  password: password
  database: vedoc-api_development
  host: database-1.c8zekncs5jhg.us-east-1.rds.amazonaws.com
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default


test:
  <<: *default
  database: vedoc-api_test

production:
  <<: *default
