default: &default
  adapter: postgresql
  encoding: unicode
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}
  host: ${DB_HOST}
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default


test:
  <<: *default
  database: vedoc-api_test

production:
  <<: *default
