default: &default
  adapter: postgis
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin_repo_development

  username: postgres

  password: 12345

  host: localhost

  port: 5432

test:
  <<: *default
  database: admin_repo_test

production:
  <<: *default
  database: admin_repo_production
  username: admin_repo
  password: <%= ENV["admin_repo_DATABASE_PASSWORD"] %>