default: &default
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV[ 'MONGO_DB' ] %>
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= ENV[ 'MONGO_HOST' ] %>
      options:
        # Change the default write concern. (default = { w: 1 })
        # write:
        #   w: 1

        # Change the default read preference. Valid options for mode are: :secondary,
        # :secondary_preferred, :primary, :primary_preferred, :nearest
        # (default: primary)
        # read:
        #   mode: :secondary_preferred
        #   tag_sets:
        #     - use: web

        # The name of the user for authentication.
        user: <%= ENV[ 'MONGO_USER' ] %>

        # The password of the user for authentication.
        password: <%= ENV[ 'MONGO_PASSWORD' ] %>

        # The user's database roles.
        # roles:
        #   - 'dbOwner'

        # Change the default authentication mechanism. Valid options are: :scram,
        # :mongodb_cr, :mongodb_x509, and :plain. Note that all authentication
        # mechanisms require username and password, with the exception of :mongodb_x509.
        # Default on mongoDB 3.0 is :scram, default on 2.4 and 2.6 is :plain.
        auth_mech: :scram

        # The database or source to authenticate the user against.
        # (default: the database specified above or admin)
        auth_source: admin

development:
  <<: *default

production:
  <<: *default
